name: Build static site (Next.js)

on:
  workflow_dispatch: {}   # ajoute le bouton "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build Next.js app
        run: npm run build || npx next build

      - name: Export static version
        run: npm run export || npx next export

      - name: Upload artifact (ZIP prêt FTP)
        uses: actions/upload-artifact@v4
        with:
          name: site-out
          path: out
